apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-showtime-api
  labels:
    app: scraping-showtime-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scraping-showtime-api
  template:
    metadata:
      labels:
        app: scraping-showtime-api
    spec:
      containers:
        - name: scraping-showtime-api-container
          image: your-registry/scraping-showtime-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: scraping-showtime-api-volume
          persistentVolumeClaim:
            claimName: scraping-showtime-api-pvc
